"""dist-stack model registry + provenance manifest library.

Re-exports the public API: the functional registry operations, the
``ModelRecord`` dataclass, the exception classes, and the provenance manifest
sidecar (``Manifest``, ``get_manifest_path``/``write_manifest``/
``read_manifest``/``has_manifest``). Nothing else is public. MCP exposure is
explicitly deferred to Phase 2 (`dist_stack.mcp`).
"""

from __future__ import annotations

from .kg import (
    IngestReport,
    KGEdge,
    KGError,
    KGNode,
    KGStats,
    KGUnavailableError,
    NodeNotFoundError,
    delete_node,
    get_kg_path,
    get_neighbors,
    get_node,
    get_provenance_chain,
    graph_stats,
    ingest,
    search_nodes,
    upsert_edge,
    upsert_node,
)
from .manifest import (
    MANIFEST_SCHEMA_VERSION,
    MANIFEST_SUFFIX,
    Manifest,
    get_manifest_path,
    has_manifest,
    read_manifest,
    write_manifest,
)
from .registry import (
    HashMismatchError,
    InvalidModelRefError,
    ModelNotFoundError,
    ModelPathNotFoundError,
    ModelRecord,
    RegistryError,
    RegistryUnavailableError,
    delete,
    ensure_schema,
    get_registry_path,
    list_models,
    lookup,
    lookup_path,
    make_model_id,
    next_version,
    register,
    resolve_model_ref,
)
from .runstore import (
    ArtifactPathNotFoundError,
    ArtifactRecord,
    RunExistsError,
    RunNotFoundError,
    RunRecord,
    RunstoreError,
    RunstoreUnavailableError,
    attach_artifact,
    create_run,
    delete_run,
    get_run,
    get_runstore_path,
    list_artifacts,
    list_runs,
    make_run_id,
    update_run,
)
from .version import __version__

__all__ = [
    "__version__",
    "register",
    "lookup",
    "lookup_path",
    "delete",
    "list_models",
    "resolve_model_ref",
    "next_version",
    "make_model_id",
    "ensure_schema",
    "get_registry_path",
    "ModelRecord",
    "RegistryError",
    "InvalidModelRefError",
    "ModelNotFoundError",
    "ModelPathNotFoundError",
    "RegistryUnavailableError",
    "HashMismatchError",
    # runstore (Phase 2)
    "create_run",
    "get_run",
    "list_runs",
    "update_run",
    "delete_run",
    "attach_artifact",
    "list_artifacts",
    "make_run_id",
    "get_runstore_path",
    "RunRecord",
    "ArtifactRecord",
    "RunstoreError",
    "RunstoreUnavailableError",
    "RunNotFoundError",
    "RunExistsError",
    "ArtifactPathNotFoundError",
    # provenance manifest sidecar (v1)
    "Manifest",
    "MANIFEST_SCHEMA_VERSION",
    "MANIFEST_SUFFIX",
    "get_manifest_path",
    "write_manifest",
    "read_manifest",
    "has_manifest",
    # kg (Phase 3)
    "upsert_node",
    "get_node",
    "search_nodes",
    "delete_node",
    "upsert_edge",
    "get_neighbors",
    "get_provenance_chain",
    "graph_stats",
    "get_kg_path",
    "ingest",
    "KGNode",
    "KGEdge",
    "KGStats",
    "IngestReport",
    "KGError",
    "KGUnavailableError",
    "NodeNotFoundError",
]
